name: PHP8 Readiness.

on: repository_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP & Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer, phpcs
    - name: Setup Environment
      run: |
        mkdir -p vendor/PHPCompatibility/PHPCompatibility
        git clone https://github.com/PHPCompatibility/PHPCompatibility vendor/PHPCompatibility/PHPCompatibility
        cd vendor/PHPCompatibility/PHPCompatibility && composer install
    - name: Checkout Plugin
      run: |
        mkdir -p plugin
        svn export $SVN_DIR plugin --force
      env:
          SVN_DIR: "${{ github.event.client_payload.svn }}"
    - name: Run PHPCompatibility checks
      run: |
        pwd && ls -lah
        ./run.sh